### ISSUE TITLE
Description of `packet_rssi` does not match dissector implementation + other unexpected behaviour

### ISSUE THREAD

**Issue by nondetalle** [eriknl/LoRaTap#2]
Hello,

I am working on a LoRa simulator to generate artificial LoRaWAN .pcap traces and I am trying to understand a couple of things.

The description of the field `packet_rssi` says that, when the SNR is negative, we need to do `packet_rssi` * .25 before adding -139  to obtain the dBm value for RSSI.
What is the reason behind that? I was looking at the Wireshark [dissector implementation](https://github.com/wireshark/wireshark/blob/master/epan/dissectors/packet-loratap.c) and this behaviour is not implemented.

Another question regarding the SNR: the description says that the `snr` field is interpreted as the two's complement, but in the dissector all values are returned as positive. Is it intentional?

Thanks.

**Comment by eriknl** [comment]
Hi!

This was designed with the SX1272 datasheet in mind. The rssi calculation was taken from there (see chapter 5.5.5. "RSSI and SNR in LoRa Mode").
Any discrepancies in the WS dissector are unintentional by the way. At that time I was mostly interested in dissecting LoRaWAN packets but had to build the whole protocol stack to get there first.

**Comment by nondetalle** [comment]
Hello!

Thank you for explaining. Maybe I should open an issue direclty on Wireshark.

I will close this one.
